### ISSUE TITLE
Error while training

### ISSUE THREAD

**Issue by shubhambaid** [leftthomas/MCDet#2]
`launch.py: error: argument --nproc_per_node: invalid int value: 'configs/reppoints_v2/reppoints_v2_r50_fpn_1x_bdd100k.py'`

Getting this error while training the reppoints_v2_r50 model

**Comment by leftthomas** [comment]
@shubhambaid this is PyTorch issues, you should make sure you have multi GPUs on your machine

**Comment by shubhambaid** [comment]
I have set GPU nos as 1 in the config as well as script

**Comment by leftthomas** [comment]
@shubhambaid if you use only 1 GPU, you can't use `dist_train.sh` to start train, you should use `train.py` to train
